export const GET_ADDRESSES_REQUESTED = 'GET_ADDRESSES_REQUESTED';
export const GET_ADDRESSES_SUCCESS = 'GET_ADDRESSES_SUCCESS';
export const GET_ADDRESSES_FAILED = 'GET_ADDRESSES_FAILED';

export const CREATE_ADDRESS_REQUESTED = 'CREATE_ADDRESS_REQUESTED';
export const CREATE_ADDRESS_SUCCESS = 'CREATE_ADDRESS_SUCCESS';
export const CREATE_ADDRESS_FAILED = 'CREATE_ADDRESS_FAILED';

export const DELETE_ADDRESS_REQUESTED = 'DELETE_ADDRESS_REQUESTED';
export const DELETE_ADDRESS_SUCCESS = 'DELETE_ADDRESS_SUCCESS';
export const DELETE_ADDRESS_FAILED = 'DELETE_ADDRESS_FAILED';
